name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
  workflow_dispatch:

jobs:
  bump:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-bumpr@v1

  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Bump version on merging Pull Requests with specific labels. (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: haya14busa/action-bumpr@v1

      # Get tag name.
      - id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      # Create release.
      - uses: actions/create-release@v1
        id: create_release
        if: ${{ steps.tag.outputs.value != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          release_name: Release ${{ steps.tag.outputs.value }}
          body: ${{ steps.bumpr.outputs.message }}
          draft: false
          prerelease: false

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        if: ${{ steps.tag.outputs.value != '' || github.event_name == 'workflow_dispatch' }}
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: ${{ steps.tag.outputs.value != '' || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        if: ${{ steps.tag.outputs.value != '' || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Docker images
        if: ${{ steps.tag.outputs.value != '' || github.event_name == 'workflow_dispatch' }}
        env:
          IMAGE_NAME: ${{ github.repository }}
          RELEASE_VERSION: ${{ steps.tag.outputs.value }}
        run: |
          # Build tags based on context
          TAGS="--tag $IMAGE_NAME:latest --tag ghcr.io/$IMAGE_NAME:latest"
          if [ -n "$RELEASE_VERSION" ]; then
            TAGS="$TAGS --tag $IMAGE_NAME:$RELEASE_VERSION --tag ghcr.io/$IMAGE_NAME:$RELEASE_VERSION"
          fi
          
          # Build the image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            $TAGS \
            --push \
            .